# Generated by Django 4.2.6 on 2023-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snowboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('P', 'Park'), ('F', 'Free-ride'), ('A', 'All mountain')], default='A', max_length=15)),
                ('type', models.CharField(choices=[('R', 'Rocker'), ('C', 'Camber')], default='C', max_length=15)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=15)),
                ('length_size', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
