# Generated by Django 4.2.6 on 2023-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowboard',
            name='reference_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
