# Generated by Django 4.2.6 on 2023-10-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0002_snowboard_reference_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snowboard',
            old_name='price',
            new_name='price_euro',
        ),
    ]
