# Generated by Django 4.2.6 on 2023-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0003_rename_price_snowboard_price_euro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='reference_link',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
