# Generated by Django 4.2.6 on 2023-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0004_alter_snowboard_reference_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=15),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='style',
            field=models.CharField(choices=[('Park', 'Park'), ('Free-ride', 'Free Ride'), ('All mountain', 'All Mountain')], default='All mountain', max_length=15),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='type',
            field=models.CharField(choices=[('Rocker', 'Rocker'), ('Camber', 'Camber')], default='Camber', max_length=15),
        ),
    ]
