# Generated by Django 4.2.6 on 2023-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0005_alter_snowboard_gender_alter_snowboard_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowboard',
            name='year',
            field=models.CharField(choices=[('2024', 'This Year'), ('2023', 'Last Year'), ('2022', 'Last Last Year')], default='2024', max_length=15),
        ),
    ]
