# Generated by Django 4.2.6 on 2023-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0006_snowboard_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowboard',
            name='true_twin',
            field=models.BooleanField(default=True),
        ),
    ]
