# Generated by Django 4.2.6 on 2023-10-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboards', '0007_snowboard_true_twin'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowboard',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate-Advanced', 'Int Adv')], default='Intermediate-Advanced', max_length=30),
        ),
    ]
